apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poker-storage
  namespace: poker
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: do-block-storage